import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const check = process.argv.slice(2);
if (check.length && (check.length !== 1 || check[0] !== "--check"))
  throw new Error("expected no arguments or --check");

const names = ["cli-result", "run-evidence", "report", "extension"];
const ajv = new Ajv2020({
  strict: true,
  strictRequired: false,
  strictTypes: false,
  code: { source: true },
});
for (const name of names)
  ajv.addSchema(
    JSON.parse(
      await readFile(join(root, `schemas/${name}-v1.schema.json`), "utf8"),
    ),
  );

const directory = join(root, "src/generated");
if (!check.length) await mkdir(directory, { recursive: true });
for (const name of names) {
  const validator = ajv.getSchema(`urn:sevro:schema:${name}:v1`)!;
  const files = {
    [`${name}.cjs`]:
      "// Generated by bun run schemas:generate; do not edit.\n" +
      standaloneCode(ajv, validator) +
      "\n",
    [`${name}.d.cts`]:
      "// Generated by bun run schemas:generate; do not edit.\n" +
      "declare function validate(value: unknown): boolean;\nexport = validate;\n",
  };
  for (const [name, content] of Object.entries(files)) {
    const path = join(directory, name);
    if (check.length) {
      const actual = await readFile(path, "utf8").catch(() => "");
      if (actual !== content)
        throw new Error(`${name} is stale; run bun run schemas:generate`);
    } else await writeFile(path, content);
  }
}
